/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author HP
 */
public class pilihGambarCombobox extends javax.swing.JFrame {

    /**
     * Creates new form pilihGambarCombobox
     */
    public pilihGambarCombobox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pilihGambar = new javax.swing.JComboBox<>();
        image = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("pilih Gambar");
        button.add(jLabel2);

        pilihGambar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laut", "Bunga", "Doll", " " }));
        pilihGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihGambarActionPerformed(evt);
            }
        });
        button.add(pilihGambar);

        getContentPane().add(button, java.awt.BorderLayout.PAGE_START);

        image.setLayout(new java.awt.CardLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Laut.jpg")); // NOI18N
        image.add(jLabel3, "0");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Bunga.jpg")); // NOI18N
        image.add(jLabel1, "1");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Doll.jpg")); // NOI18N
        image.add(jLabel4, "2");

        getContentPane().add(image, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihGambarActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) image.getLayout();
    String selectedOption = (String) pilihGambar.getSelectedItem();
    if (!"Pilih Disini".equals(selectedOption)) {
    switch (selectedOption) {
        case "Laut":
        cardLayout.show(image, "0");
        break;
        case "Bunga":
        cardLayout.show(image, "1");
        break;
        case "Doll":
        cardLayout.show(image, "2");
        break;
        
        default:
           
        break;
        }
        
        }
        
    }//GEN-LAST:event_pilihGambarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihGambarCombobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button;
    private javax.swing.JPanel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> pilihGambar;
    // End of variables declaration//GEN-END:variables
}
